### ISSUE TITLE
Weird display bug, incoherent display with equivalent json files

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#106]
Hi,

I got this kind of crazy bug when I use perfetto. I got this very simple chrome trace format compatible json file:

```
{"traceEvents":[{"pid":1805,"tid":1805,"ts":9089707.546,"dur":1001126.1,"name":"time.sleep","caller_lineno":4,"ph":"X","cat":"FEE"},{"pid":1805,"tid":1805,"ts":9089706.346,"dur":1001131.8,"name":"<module> (/home/gaogaotiantian/programs/codesnap/scrabble4.py:1)","caller_lineno":237,"ph":"X","cat":"FEE"},{"pid":1805,"tid":1805,"ts":9089705.746,"dur":1001136.6,"name":"builtins.exec","caller_lineno":237,"ph":"X","cat":"FEE"}],"displayTimeUnit":"ns"}
```

I loaded with perfetto, as you can see, the timeline shows this takes about 1ms. I'm not sure how ``displayTimeUnit`` works here but just continue.

![image](https://user-images.githubusercontent.com/13121107/110220238-00883080-7e79-11eb-8864-98f39146f220.png)

After getting this result, I used a json linter to the exact same json file, and stored it to another json file:

```
{
	"traceEvents": [{
		"pid": 1805,
		"tid": 1805,
		"ts": 9089707.546,
		"dur": 1001126.1,
		"name": "time.sleep",
		"caller_lineno": 4,
		"ph": "X",
		"cat": "FEE"
	}, {
		"pid": 1805,
		"tid": 1805,
		"ts": 9089706.346,
		"dur": 1001131.8,
		"name": "<module> (/home/gaogaotiantian/programs/codesnap/scrabble4.py:1)",
		"caller_lineno": 237,
		"ph": "X",
		"cat": "FEE"
	}, {
		"pid": 1805,
		"tid": 1805,
		"ts": 9089705.746,
		"dur": 1001136.6,
		"name": "builtins.exec",
		"caller_lineno": 237,
		"ph": "X",
		"cat": "FEE"
	}],
	"displayTimeUnit": "ns"
}
```

They are literally the same json from json point of view. I loaded with perfetto, and it showed the program took 1s:

![image](https://user-images.githubusercontent.com/13121107/110220280-64125e00-7e79-11eb-9f87-0e1557e39e20.png)

I can reproduce this reliably on my computer. There are definitely some issues here.

As a comparison, Catapult Trace Viewer has a coherent behavior and it's expected, whereas timestamp unit is always in "us" and "displayTimeUnit" only affects the granularity of the UI.

**Comment by chromy** [comment]
Thanks for the report @gaogaotiantian!

So there are two quite unfortunate things going on here, both of which are my fault.
1. `trace_processor` handles `displayTimeUnit` differently depending on how the key is to the start of the file.
2. `trace_processor` uses `displayTimeUnit: <unit>` to mean "`ts` is recorded in these `<units>s`" which is not what catapult implements or what [the specification](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.q8di1j2nawlp) says.

In more detail:
1. `trace_processor` was designed to be able to quickly parse very large (protobuf) trace files. To meet this goal it tries to avoid needing information from the end of the file in order to understand information at the beginning of the file. This lets it parse the whole trace in one pass with minimal additional memory use. The protobuf format is carefully designed to support this. Historically we had some hacks to achieve similar things for .json traces. Rather than parsing the whole trace as a single large javascript object (and paying the memory cost of this) we extracted the individual events with some hand rolled parsing code. When I [added support](https://android-review.googlesource.com/c/platform/external/perfetto/+/1224818/) for `displayTimeUnit` this became a problem. We need to know the `displayTimeUnit` before we parse the `traceEvents` but `displayTimeUnit` could legitimately be the last key in the file. I 'handled' this by using `displayTimeUnit` if we see it early in the file (specifically in the first chunk we read from the file) and ignoring it otherwise. You can see the code [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/json/json_trace_tokenizer.cc;l=285?q=displayTimeUnit). This explains the unfortunate difference in behaviour you noticed between the linted and unlinted files even though they ought to be equivalent ...as you might be able to tell from the long explanation I regret a lot of that.
 
2. We initially landed support for `displayTimeUnit` for an internal client, based on how they thought it worked and at the time I didn't spend enough time looking at the spec and checking what catapult actually did before implementing this. As you mentioned in catapult displayTimeUnit doesn't affect the parsing of the file.

In terms of next steps for Perfetto I suggest:

1. We should add an [error counter](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/storage/stats.h;l=170?q=f:perfetto%20error%20f:trace_processor%20f:h$) which is populated if `displayTimeUnit` ends up being ignored. That way people will at least be able to tell when this happens.
2. We should consider if it's possible to make the json importer more sensible, over time as we've added support for more of the json trace event format it's become pretty complicated.
3. The situation with `displayTimeUnit` is pretty bad, looking around I think only a handful of internal customers that reply on the new behaviour. Maybe we can ask them to move to a new key (`traceTimeUnit` or something)? Then we can update the parsing code in `trace_processor` and unbreak all the other trace producers.

@gaogaotiantian: it will take some time to fix these (particularly 3. since even after we fix it we'll need some time period where clients can open their old traces and keep the current behaviour). If you would like to use the UI currently I would suggest not emitting `displayTimeUnit` at all if possible.

### Data

The first example:
[bad-displayTimeUnit.json.txt](https://github.com/google/perfetto/files/6096451/bad-displayTimeUnit.json.txt)

The linted version:
[formatted-bad-displayTimeUnit.json.txt](https://github.com/google/perfetto/files/6096449/formatted-bad-displayTimeUnit.json.txt)

- catapult:
<img width="1348" alt="Screenshot 2021-03-06 at 18 54 09" src="https://user-images.githubusercontent.com/351085/110227440-76a68a80-7ead-11eb-8836-7a73fc80b760.png">

- formatted catapult:
<img width="1348" alt="Screenshot 2021-03-06 at 18 54 18" src="https://user-images.githubusercontent.com/351085/110227439-6bebf580-7ead-11eb-8ba7-bf44a7f31001.png">

- perfetto
<img width="1348" alt="Screenshot 2021-03-06 at 18 54 02" src="https://user-images.githubusercontent.com/351085/110227448-7c9c6b80-7ead-11eb-8dc4-8ca907ba73f1.png">

- formatted perfetto
<img width="1348" alt="Screenshot 2021-03-06 at 18 54 06" src="https://user-images.githubusercontent.com/351085/110227445-7a3a1180-7ead-11eb-80cf-4aeaf087c2ef.png">

**Comment by gaogaotiantian** [comment]
Okay I can understand the logic and the tradeoffs behind this bug. 

The problem I'm having now is that I need to support both perfetto and catapult for a while, until I can completely move to perfetto. Removing ``displayTimeUnit`` completely is not viable now because that will change the granularity of catapult, resulting in wrong display(ns level slice will be broken). It seems like perfetto does not have this issue. However, there's still not a way to have a json file that can work perfectly on both perfetto and catapult. So, I'm expecting that this could be solved in the future.

I totally agree with 1. and 3., and I don't have a strong opinion about 2. I know this could take time, ``viztracer`` only started to promote perfetto support recently and it is still more focused on catapult, so this would not be a huge problem for me.

Thank you for your detailed explanation and I hope perfetto becomes perfetto :)

**Comment by gaogaotiantian** [comment]
@chromy is this issue secretly fixed(at least the fact ``displayUnit`` is determined by its location in the file)? I seem to experience different behaviors now.

**Comment by primiano** [comment]
I think commit 72543fdae531d103f2165789be243b4c5c9e2194 did it. We forgot to mention this Github issue (we mirrored the bug internally and mistakenly only referenced that), so that's why this was "secretly" fixed :)

Thanks for the report.

**Comment by gaogaotiantian** [comment]
So now perfetto behaves consistently different than catapult? Will it keep this way or it will be changed in the future? aka will ``displayTimeUnit`` determines the timestamp unit or it only affects the minimum granularity of the UI(I think this might be a catapult only thing?).

**Comment by LalitMaganti** [comment]
I don't think there's any further changes planned for JSON parsing ATM.

**Comment by gaogaotiantian** [comment]
Okay so it will keep this way. Is JSON format a backward compatibility thing, or that's actively supported? There are plenty of features in Chrome JSON format that's not supported(even it's doable in UI), for example, constant events and counter events. Is there a plan to support that in the future, or all the efforts will be in protobuf format?

**Comment by primiano** [comment]
Our plan is to be backwards compatible with the JSON emitted by chrome://Tracing.
For the rest there are too many possible creative variants w.r.t unspecified behaviours that other projects took and happened to work by accident. We cannot possibly know all of them upfront. We'll deal with them on a case-by-case basis (like this).

> for example, constant events 

What is "constant events"?

> and counter events.

Aren't those supported already?

**Comment by gaogaotiantian** [comment]
Sorry that's my typo, I meant "instant events".

I don't think counter events are supported. There are UI components in the front end and you can do it in protobuf, but it can't parse from JSON.

For example:
```
[
    {"pid": "1000", "name": "ctr", "ph": "C", "ts":  0, "args": {"cats":  0}},
    {"pid": "1000", "name": "ctr", "ph": "C", "ts": 10, "args": {"cats": 10}},
    {"pid": "1000", "name": "ctr", "ph": "C", "ts": 20, "args": {"cats":  0}}
]
```

This will show a counter track in catapult, but nothing in perfetto. Same as instant events. They are both documented in https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU which I guess is some kind of official documentation?

**Comment by primiano** [comment]
Uh actually you are right, they don't seem there.
Those are valid use-cases and as you say part of the official spec.
We should add them.

**Comment by gaogaotiantian** [comment]
Great! Looking forward to it. Those will make my work easier!

**Comment by LalitMaganti** [comment]
Adding counter and instant events is tracked by the internal bug b/149914833 and I plan on addressing it as part of our fixit this week.

**Comment by gaogaotiantian** [comment]
Wait I'm confused now. Seems like the latest version changed the ``displayTimeUnit`` behavior again? Now that key does not have any effects? Could you tell me what is the expected behavior of ``displayTimeUnit`` now?

```
{"traceEvents": [{"pid": 1, "tid": 1, "name": "test", "ts": 1, "dur": 1000, "ph": "X", "cat": "fee"}], "displayTimeUnit": "ms"}
```

```
{"traceEvents": [{"pid": 1, "tid": 1, "name": "test", "ts": 1, "dur": 1000, "ph": "X", "cat": "fee"}], "displayTimeUnit": "us"}
```

Are these two supposed to have exact same output on Perfetto(just like on catapult)?

**Comment by LalitMaganti** [comment]
There's been no change to displayTimeUnit since this commit https://github.com/google/perfetto/commit/e569a2493d977afc9379e4ee57de14a535db3335 15 months ago.

Your JSON uses `us` as a unit which is not supported - see the trace above.

Also small update: we just landed support for counter and instant events in JSON in https://github.com/google/perfetto/commit/4018d1c7626a40af1fd01c4990a0f36437d4abd1 so that should now work.

**Comment by gaogaotiantian** [comment]
Okay I think I got what's going on here. I've been getting some mixed messages unfortunately.

First of all, the original bug in this issue is still not fixed. The position of ``displayTimeUnit`` still determines the output of the UI, which I still consider as a bug. It makes no sense two equivalent JSON generates different outputs.

While I'm digging into this, I found another unfortunate bug:
![image](https://user-images.githubusercontent.com/13121107/119021714-9994f680-b954-11eb-9da3-29743d48a705.png)
This code does not check for spaces.

In other words
```
{"displayTimeUnit": "ms"} // with space
```
and
```
{"displayTimeUnit":"ms"} // without space
```
is treated differently. The latter takes effect and the former does not. This is the reason my examples in https://github.com/google/perfetto/issues/106#issuecomment-843725080 won't work. Even if ``"us"`` is not supported, that's the default option so ``ms`` should work and give a different output, but it's not. Deleting the space before ``"ms"`` works.

This should be a bug as well and I'm not sure how hard it is to fix it in cpp. It's trivial in python or JavaScript with RegEx module and as it will only be executed once, the extra constant time consuming should not be a big issue.

BTW, thanks for the update of instant and counter events! I'll check it out.

**Comment by LalitMaganti** [comment]
So with respect to JSON parsing in trace processor: JSON parsing is supported purely on a best effort basis with priority fixing issues with Chrome traces. While I appreciate that many other people other than Chrome have used the JSON format, we simply do not have the bandwidth to add support for the full tracing format as implemented by Catapult.

With that said, addressing each of the issues you have raised in turn:
> The position of displayTimeUnit still determines the output of the UI.
I agree this is a bug. Unfortunately, there are two major constraints trace processor imposes which makes solving this issue difficult:
1. We avoid ingesting the full JSON trace into memory so we can support O(GB) traces
2. We need to know the `displayTimeUnit` before we parse the first event as retroactively fixing timestamps is too hard.

Because of this, I'd say this issue is infeasible to fix at this time so we would *not* be improving this logic any further beyond what we do today (scan for the `displayTimeUnit` in the first chunk of the trace passed to trace processor).

> This code does not check for spaces.
I agree this is also a bug and much easier to fix. I'll look into this either tomorrow or some point next week and send a patch.

**Comment by gaogaotiantian** [comment]
Okay I understand the tradeoff for ``displayTimeUnit`` and I can deal with it in my own code. It just the comments in https://github.com/google/perfetto/issues/106#issuecomment-792238450 made me leave this issue open. For example, an error was mentioned to avoid silent ignore. However, if that won't be implemented, I'm fine with it too.

Thanks for the effort to explain and fix related problems, you can close this issue when you fix the space bug.

**Comment by LalitMaganti** [comment]
Adding an error counter for `displayTimeUnit` if it's seen in the trace is also feasible. I'll look into implementing this also.

**Comment by LalitMaganti** [comment]
Both the error counter and corrected parsing has been implemented in https://android-review.googlesource.com/c/platform/external/perfetto/+/1720792

Should land early next week.

**Comment by gaogaotiantian** [comment]
Thanks. Feel free to close this issue when you think it's appropriate.

**Comment by LalitMaganti** [comment]
https://github.com/google/perfetto/commit/b5072a9e9d0f130e505df835c0250efc9fa970da has landed so closing this bug.
